services:

  web:
    build:
      context: .
      dockerfile: ./apps/gym-web-app/Dockerfile.dev
    restart: "no"
    environment:
      - NODE_ENV=development
    command: ["npx", "nx", "serve", "gym-web-app"]
    volumes:
      - ./:/app

  api:
    build:
      context: .
      dockerfile: ./apps/gym-api/Dockerfile.dev
    command: ["doppler", "run", "--", "npx", "nx", "serve", "gym-api"]
    restart: "no"
    environment:
      - NODE_ENV=development
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    volumes:
      - ./:/usr/src/app
  
  workers:
    build:
      context: .
      dockerfile: ./apps/workers/Dockerfile.dev
    command: ["doppler", "run", "--", "npx", "nx", "serve", "workers"]
    restart: "no"
    environment:
      - NODE_ENV=development
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    volumes:
      - ./:/usr/src/app
