version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./apps/gym-web-app/Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  api:
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: ./apps/gym-api/Dockerfile

  workers:
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: ./apps/workers/Dockerfile
