version: '3.8'

services:
  gym-web-app:
    build:
      context: .
      dockerfile: ./apps/gym-web-app/Dockerfile
    ports:
      - "4200:80"
    restart: always
    environment:
      - NODE_ENV=production
  gym-api:
    build:
      context: .
      dockerfile: ./apps/gym-api/Dockerfile
    healthcheck:
      test: ["CMD", "node", "./scripts/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "3000:3000"
  mongo:
    image: mongo:7.0.2
    container_name: mongo
    hostname: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: ["CMD", "bash", "./scripts/mongodb-healthcheck.sh"]
      interval: 60s
      timeout: 10s
      retries: 5
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
  mongodb_config:

networks:
  gym-network: