services:

  web:
    build:
      context: .
      dockerfile: ./apps/gym-web-app/Dockerfile.dev
    restart: "no"
    environment:
      - NODE_ENV=development
    command: ["npx", "nx", "serve", "gym-web-app"]
    volumes:
      - ./:/app

  api:
    build:
      context: .
      dockerfile: ./apps/gym-api/Dockerfile.dev
    command: ["doppler", "run", "--", "npx", "nx", "serve", "gym-api"]
    restart: "no"
    environment:
      - NODE_ENV=development
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - DOPPLER_PROJECT=${DOPPLER_PROJECT}
      - DOPPLER_CONFIG=${DOPPLER_CONFIG}
    volumes:
      - ./:/usr/src/app
    extra_hosts:
      - "auth.localhost:172.17.0.1"

  workers:
    build:
      context: .
      dockerfile: ./apps/workers/Dockerfile.dev
    command: ["doppler", "run", "--", "npx", "nx", "serve", "workers"]
    restart: "no"
    environment:
      - NODE_ENV=development
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - DOPPLER_PROJECT=${DOPPLER_PROJECT}
      - DOPPLER_CONFIG=${DOPPLER_CONFIG}
    volumes:
      - ./:/usr/src/app

  keycloak:
    command: start-dev --import-realm

  postgres:
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - auth-network