version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  api:
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: ./apps/gym-api/Dockerfile
