services:

  web:
    build:
      context: .
      dockerfile: ./apps/gym-web-app/Dockerfile.dev
    restart: "no"
    environment:
      - NODE_ENV=development
    command: ["npx", "nx", "serve", "gym-web-app"]
    volumes:
      - ./:/app

  api:
    build:
      context: .
      dockerfile: ./apps/gym-api/Dockerfile.dev
    command: ["npx", "nx", "serve", "gym-api"]
    restart: "no"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
