FROM node:18 AS gym-web-app-base

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm@9.9.0 

RUN pnpm install --frozen-lockfile

COPY . .

CMD ["npx", "nx", "serve", "gym-web-app"]
