FROM node:18-alpine AS gym-api-base

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm@9.9.0

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["npx", "nx", "serve", "gym-api", "--host", "0.0.0.0"]