FROM node:18-alpine AS gym-api-base

WORKDIR /usr/src/app

RUN apk update && apk add --no-cache netcat-openbsd

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm@9.9.0

RUN pnpm install --frozen-lockfile

COPY . .

CMD ["npx", "nx", "serve", "gym-api"]