FROM node:20.17.0-alpine AS base

WORKDIR /build

RUN apk add --no-cache bash curl gnupg python3 make g++ && \
    npm install -g pnpm@9.12.0 && \
    curl -Ls https://cli.doppler.com/install.sh | sh

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .