name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

env:
  NX_NO_CLOUD: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
          dest: ~/setup-pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm run ci

      - name: Lint all projects
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
          dest: ~/setup-pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm run ci

      - name: Build all projects
        run: npm run build

  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
          dest: ~/setup-pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm run ci

      - name: Test all projects
        run: pnpm run test
