name: CI

on:
  push:
    branches: [main]
    paths:
      - 'apps/**'
      - 'libs/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/**'
      - 'libs/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'

defaults:
  run:
    shell: bash

env:
  NX_NO_CLOUD: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/reusable-setup.yml
      - name: Lint all projects
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/reusable-setup.yml
      - name: Build all projects
        run: npm run build

  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/reusable-setup.yml
      - name: Test all projects
        run: pnpm run test
