name: CI

on:
  push:
    branches: [main]
    paths:
      - 'apps/**'
      - 'libs/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/**'
      - 'libs/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'

defaults:
  run:
    shell: bash

env:
  NX_NO_CLOUD: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
          dest: ~/setup-pnpm
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm run ci
      - name: Lint all projects
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
          dest: ~/setup-pnpm
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm run ci
      - name: Build all projects
        run: npm run build

  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
          dest: ~/setup-pnpm
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm run ci
      - name: Test all projects
        run: pnpm run test
